name = "integration"
main = "backend/src/server.ts"
compatibility_date = "2024-12-22"

# workers_dev = false
route = {pattern = "integrations.ladavila.com", zone_name = "ladavila.com", custom_domain = true}

# Observer
[build]
command = "pnpm build"
cwd = "frontend"
watch_dir = "frontend/src"

[site]
bucket = "frontend/dist"